### ISSUE TITLE
V1.0.5 Only Allows Symlink Deployment (and removes Hardlink Deployment)

### ISSUE THREAD

**Issue by SSyl** [Nexus-Mods/game-valheim#1]
As soon as I updated to the latest version of the Valheim Extension in Vortex I was met with a notification saying "Deployment Method No Longer Supported" or something along those lines.

I only use Hardlink deployment when I use Vortex as I find Symlink deployment to be somewhat unreliable as it doesn't always actually deploy my mods. With Hardlinks I never run into that issue.

I clicked to see more information and I was met with this:

![image](https://user-images.githubusercontent.com/6855315/114231271-d2968000-993f-11eb-8bcb-f87cc93472ec.png)

That error message would make sense if my mods or game were on a different drive, however I never moved my mods or my game installation, as you can see in the following screenshots:

![image](https://user-images.githubusercontent.com/6855315/114232326-4f762980-9941-11eb-9775-93cb85c9e622.png)

You can also see in the screenshot above that my only option for deployment is through Symlinks.

![image](https://user-images.githubusercontent.com/6855315/114231861-9dd6f880-9940-11eb-8c8e-09451a3dacdc.png)

As you can see, my D drive contains both the game and my mods. On top of that, Vortex itself is installed on the D drive.

Reverting back to v1.0.4 and then restarting Vortex fixes the issue. As soon as I update to v1.0.5 again the problem comes back.

--

On a somewhat related issue, Valheim always chooses to default to Symlink on new installations (happened on 3 of my PCs as well as my friend's PC) when it should default to Hardlink because the mods and game are setup in the same folder. I'm not sure if that's an issue with this extension or if that's a Vortex issue in general.

**Comment by IDCs** [comment]
Hey @SSyl thanks for your report - this is an unexpected side effect of adding support for world maps in 1.0.5 which are deployed to the AppData folder on the "C:" drive.

Vortex sees that the game is located on "D:" and that some mods are supposed to be deployed on "C:" and automatically disables the hardlink deployment method. Needless to say this needs to be rectified immediately - I also prefer using hardlinks but as my game and staging folder are both located on "C:" I didn't notice this side effect.

I'll make sure this is fixed in 1.0.6, but in the meantime you have two options. Either stick with version 1.0.4 of the extension or move the game to "C:\"

**Comment by IDCs** [comment]
This is fixed in https://github.com/Nexus-Mods/game-valheim/commit/74c95a45fb38c853993467fdbafcb68461831c1d

Will try to upload this today but as we don't usually work weekends and none of my colleagues are in the office right now - there might be some delay.
