### ISSUE TITLE
Start-Up Message Confirming BepInEx/Configuration Manager Install

### ISSUE THREAD

**Issue by Deadmano** [Nexus-Mods/game-valheim#5]
Any chance we can get a message on start asking if a user indeed wants to install BepInEx/Configuration Manager? To avoid hassles? I understand why there is a tight coupling, but at times it really causes more hassles, especially with collections, or requiring a higher BepInEx version but the extension is outdated.

The configurmation Manager should be optional/not installed by default as it is not required for any mods to work, and is simply a convenience tool, but can cause conflict in the case where a user installs another Configuration Manager such as [aedenthorn's version](https://www.nexusmods.com/valheim/mods/740).

There could then be a check to see if a user has BepInEx installed at all, and if not, refuses to deploy and gives the user an error offering them to install the payload on hand, or linking to the source that may have a newer version to be installed manually.

**Comment by IDCs** [comment]
Hi @Deadmano, apologies for the late reply - version 1.0.20 of the extension will no longer auto download/install the configuration manager. As far as BepInEx is concerned however - I'm afraid that most of the users are not proficient enough to download their own package, which will lead to us being swarmed with bug reports caused by incorrect mod loader installations.

I understand that us controlling the payload is frustrating when a new BepInEx package is released, but you have to understand we're only 2 developers catering for around 100k daily users; by controlling the payload, we minimize the number of users messing up their mod setups. I'm afraid the payload will remain as is.

When it comes to releasing a new BepInEx payload I'm usually quite responsive as long as I'm informed that the package needs updating, and it only takes me ~10 minutes to test the payload and release a new version.

**Comment by Deadmano** [comment]
Thanks for the reponse, @IDCs and for everything you guys do to keep this project alive! Totally understandable when it comes to BepInEx, as I can imagine how that can lead to a whole host of issues (and a headache for you guys).

Thanks for removing the Configuration Manager by default, that makes things a lot easier with mod packs!
